# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [4]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [6]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [11]:
y =  [1,2,0,0,4,0]
np.nonzero(y)

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [13]:
np.eye(3), np.identity(3)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [15]:
np.random.random((3,3,3))

array([[[0.19362699, 0.21930739, 0.26805135],
        [0.05461487, 0.11993754, 0.43293389],
        [0.35937907, 0.18074505, 0.88072935]],

       [[0.64099709, 0.83284781, 0.07908281],
        [0.15457978, 0.70628329, 0.48774019],
        [0.37465291, 0.33459851, 0.24114738]],

       [[0.92797727, 0.73415931, 0.07066134],
        [0.57541119, 0.46912574, 0.7710382 ],
        [0.19890336, 0.96519296, 0.58734159]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [49]:
r = np.random.random((10,10))
np.amin(r), np.amax(r),\
r.min(), r.max()

(0.005061583846218687,
 0.9856504541106007,
 0.005061583846218687,
 0.9856504541106007)

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [24]:
np.mean(np.random.random(30))

0.5831591434177786

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [33]:
np.random.seed(42)
rr = np.random.random((5,5))
rr.diagonal(-1)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [50]:
_max, _min = rr.max(), rr.min()
rn = (rr - _min)/(_max - _min)
rn

array([[0.37284965, 0.9797798 , 0.74938422, 0.60893137, 0.14266357],
       [0.14263816, 0.03950081, 0.89072903, 0.61151903, 0.72418595],
       [0.        , 1.        , 0.85519484, 0.20199041, 0.16984743],
       [0.17151129, 0.2987993 , 0.53108445, 0.4333188 , 0.28509156],
       [0.62283009, 0.12525671, 0.28605594, 0.36423482, 0.45873155]])

Don't know which of the two (see cell above or below) is correct, because I'm lack some math skills :}

In [54]:
_mean = np.mean(rr)
_std = np.std(rr)

(rr - _mean)/_std

array([[-0.23709911,  1.82467557,  1.04200929,  0.56488331, -1.01905371],
       [-1.01914002, -1.36950322,  1.52216525,  0.57367372,  0.95640937],
       [-1.5036896 ,  1.89336468,  1.40145369, -0.81751722, -0.92670866],
       [-0.92105645, -0.48865218,  0.30043311, -0.03168212, -0.5352181 ],
       [ 0.61209803, -1.07818578, -0.53194206, -0.26636415,  0.05464636]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [57]:
r1 = np.array([1,2,3,4,5])
r2 = np.array([[1,6,3,7,2],[22,7,45,1,2]])

np.intersect1d(r1, r2)

array([1, 2, 3])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [61]:
np.sort(np.random.random(10))

array([0.16949275, 0.29444889, 0.31692201, 0.38509773, 0.42818415,
       0.85113667, 0.85300946, 0.92831856, 0.96361998, 0.96665482])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [76]:
np.random.seed(69)
rrr = np.random.random(10)
print(rrr)
print(rrr.max())
rrr_ = np.where(rrr == rrr.max(), 0, rrr)
print(rrr_)

# rrr[np.argmax(rrr)] = 0

[0.29624916 0.80906772 0.35025253 0.78940926 0.56134898 0.25358895
 0.10497708 0.05846073 0.67329238 0.69782966]
0.8090677156733267
[0.29624916 0.         0.35025253 0.78940926 0.56134898 0.25358895
 0.10497708 0.05846073 0.67329238 0.69782966]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

Not quite clear what to substract from where!?

In [120]:
np.random.seed(69)
rrr = np.random.random(10).reshape(5,2)
print(rrr,"original array")
print("---")
row_means = rrr.mean(axis=1, keepdims=True)
row_means = [row_means[_][0] for _ in range(len(row_means))]
print(row_means, "row means")
print("---")
for idx, mean in enumerate(row_means):
    rrr[idx,0] = rrr[idx,0] - mean
    rrr[idx,1] = rrr[idx,1] - mean
    
print(rrr, "array with substracted means")

[[0.29624916 0.80906772]
 [0.35025253 0.78940926]
 [0.56134898 0.25358895]
 [0.10497708 0.05846073]
 [0.67329238 0.69782966]] original array
---
[0.5526584386728801, 0.569830890827152, 0.40746896499535284, 0.08171890644099439, 0.6855610188857771] row means
---
[[-0.25640928  0.25640928]
 [-0.21957837  0.21957837]
 [ 0.15388001 -0.15388001]
 [ 0.02325818 -0.02325818]
 [-0.01226864  0.01226864]] array with substracted means


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

This doesn't make sense because the array has initially been shuffled and I'm just resorting it again but ¯\_(ツ)_/¯

In [142]:
Z = np.arange(10000)
n = 5
np.random.shuffle(Z)
z_sort = np.sort(Z)
z_sort[-5:]

array([9995, 9996, 9997, 9998, 9999])

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [150]:
np.random.seed(123)
m = np.random.randint(0,10,(5,3))
print(m, "original array")
print("---")
m = np.where(m > 4, m**2, m) # np.where(if condition [m>4], then [m**2], else [m])
print(m, "edited array")

[[2 2 6]
 [1 3 9]
 [6 1 0]
 [1 9 0]
 [0 9 3]] original array
---
[[ 2  2 36]
 [ 1  3 81]
 [36  1  0]
 [ 1 81  0]
 [ 0 81  3]] edited array
